---
- name: create jenkins and tomcat for ci-cd
  hosts: all
  tasks:
    - name: create a jenkins container
      docker_container:
        name: myjenkins
        image: jenkins/jenkins
        ports:
          - 5050:8080

    - name: create tomcat server on QAserver and prodserver
      docker_container:
        name: "{{item.a}}"
        image: tomcat
        ports: "{{item.b}}"
      with_items:
        - {a: qaserevr,b: "6060:8080"}
        - {a: prodserver,b: "7070:8080"}
