--- 
- name: create 10 nginx containers
  hosts: all
  tasks:
    - name: create nginx containers
      docker_container:
        name: "container{{item}}"
        image: nginx
      with_sequence: count=10
      
