---
- name: Install docker required softwares
  hosts: all
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: Download Docker and execute it then install docker-py
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o install-docker.sh
        - sh install-docker.sh
        - pip3 install docker-py
