---

- name: Implementing s/w using loops
  hosts: all
  tasks:
    - name: Install s/w 
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items: 
        - {a: git,b: present,c: yes}
        - {a: maven,b: absent,c: no}
        - {a: tree,b: present,c: yes}
