---

- name: copy file1 from server1 to server2
  hosts: 172.31.18.20
  tasks:
    - name: fetch file1 from server1
      fetch:
        src: file1
        dest: /tmp
- name: Copy file1 into server2
  hosts: 172.31.23.197
  tasks:
    - name: copy file1 in server2
      copy:
        src: /tmp/172.31.18.20/file1
        dest: /tmp
