---
- name: create users/folder
  hosts: all
  tasks:
    - name: create user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        comment: "a friendly user"
        home: /tmp/chandu
    - name: create a folder
      file:
        name: "{{d}}"
        state: "{{e}}"
        mode: "{{f}}"
        owner: "{{g}}"

...
